### ISSUE TITLE
What is the recommended number of GPUs for training?

### ISSUE THREAD

**Issue by TuotuoLi** [LansburyCH/relightable-nr#2]
Hi Lansbury
Thanks for sharing the impressive work!
I have running into the following error, any insight on this problem?

Traceback (most recent call last):
  File "train_rnr.py", line 304, in <module>
    lp_stitch_resize = torch.from_numpy(lp_stitch_resize).to(device)
RuntimeError: CUDA error: invalid device ordinal

Does the code requires more than one GPU?

Best,
tuotuo

**Comment by LansburyCH** [comment]
Hi Tuotuo,
The code can also work when there is only one GPU, but you need to change the training option from ```--gpu_id 0,1``` to ```--gpu_id 0```. 

When using 2 GPUs, the gcn network is allocated on the first GPU while the rest are allocated on the second GPU. This is only necessary when the RAM of a single GPU is not enough.

**Comment by TuotuoLi** [comment]
That works, thanks for the help!!
