### ISSUE TITLE
Deferred neural rendering

### ISSUE THREAD

**Issue by darthgera123** [LansburyCH/relightable-nr#4]
Hi @LansburyCH  awesome work
Could you please share your DNR implementation? We needed to compare it with our current research. TIA

**Comment by LansburyCH** [comment]
Hi @darthgera123, I have not cleaned up my codes for DNR. But you can try [this repo](https://github.com/SSRSGJYD/NeuralTexture), which seems to be a good alternative.

**Comment by darthgera123** [comment]
Hi thanks for responding. I tried that implementation and I am getting some artifacts while rendering. Hence why i was requesting for your implementation

**Comment by LansburyCH** [comment]
It will take some time for me to update DNR into this repo. I will let you know when it is finished.

**Comment by darthgera123** [comment]
I understand. Thanks a lot. looking forward to it

**Comment by LansburyCH** [comment]
Hi @darthgera123, the DNR implementation is now in the repo. You can refer to README (near the bottom) on how to use it.

**Comment by darthgera123** [comment]
Hi Thanks a ton for this
