### ISSUE TITLE
Second lightning under the different camera poses

### ISSUE THREAD

**Issue by SavvaI** [LansburyCH/relightable-nr#7]
Hi! Thank you for the astonishing work! Could you please clarify, is it possible to use for the second lightning conditions (rgb1) photos taken under the different camera poses (and even maybe the different number of the photos)

**Comment by LansburyCH** [comment]
For training, we only need photos under one lighting condition. So the second lighting photos (rgb1) are only for visualization in tensorboard. In my current codes, I have fixed the camera poses to be the same for rgb0 and rgb1. But definitely, you can modify the codes to support different camera poses. Also, if you don't need relighting visualization during training, you can just remove rgb1. During inference, you can set any camera poses and lighting conditions as you like.
